### PR TITLE
Fixing version

### PR DESCRIPTION
**Pull request by marinaserranomontes**

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/opentok/screen-sharing-acc-pack/pull/25" target="_blank">ReviewNinja

**Comment by Lucashuang0802** [comment]
👍

**Comment by marinaserranomontes** [comment]
👍

**Comment by marinaserranomontes** [comment]
LGTM

**Comment by marinaserranomontes** [comment]
👍

**Pull request merged**
