### PR TITLE
OTS-433: added Nullability compatibility

### PR DESCRIPTION
**Pull request by jvalli**

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/opentok/screen-sharing-acc-pack/pull/16" target="_blank">ReviewNinja

**Comment by Lucashuang0802** [comment]
The whole purpose of this PR is to make Swift compatible from the screen-sharing library codes. There are no points to add nullability to the sample app level.

**Comment by jvalli** [comment]
PR updated

**Comment by Lucashuang0802** [comment]
Let's hold it for now.

**Pull request closed without merging**
